name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-rust
        if: ${{ env.ACT }}
      - uses: jwlawson/actions-setup-cmake@v1.13
        if: ${{ env.ACT }}
        with:
          # Version installed on ubuntu-22.04
          cmake-version: '3.27.3'
      - uses: KengoTODA/actions-setup-docker-compose@v1
        if: ${{ env.ACT }}
        with:
          # Version installed on ubuntu-22.04. There's also v2.20.3 installed
          # but it fails with:
          #   network compose_default was found but has incorrect label
          #   com.docker.compose.network set to ""
          version: '1.29.2'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            bommer/bommer-ui/target/
            spog/ui/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compose
        run: |
          docker-compose -f deploy/compose/compose.yaml up -d

      - name: Test
        run: |
          RUST_LOG=tantivy=off,info cargo test -p integration-tests -- --nocapture
          docker-compose -f deploy/compose/compose.yaml ps

      - name: Print logs
        if: always()
        run: |
          docker ps -a
          docker-compose -f deploy/compose/compose.yaml logs
          docker-compose -f deploy/compose/compose.yaml down
